### PR TITLE
Added tooltips to rewards section

### LINKED ISSUE #373: Give tooltips to small icons
image
Give tooltips to the small icons of the rewards page.
https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=4784%3A17941

### PR DESCRIPTION
**Pull request by Mi-Lan**
closes #373

### CODE REVIEW

**Comment by 0xVenky** [comment]
Tested and works as expected. :)

**Comment by 0xVenky** [comment]
Seems to be broken now, cant see any tool tip @luzzif  :)

**Comment by zamli** [comment]
Also tested, tooltips seems broken and not popping up

**Comment by luzzif** [comment]
They only pop up once the USD value is shown. They won't show up even then??

**Comment by zamli** [comment]
> They only pop up once the USD value is shown. They won't show up even then??

they are only showing on USD value. The purpose of the tooltips was to show the name of tokens while hover hover the tokens.
See https://github.com/levelkdev/dxswap-dapp/issues/373.

I'll send an example where its nearly impossible to see what tokens you getting rewarded:
See here: 
https://bafybeihnt7jgok2mzwvpsl3huzpdqtaylubhbprnilf3fxmg5nsq3wq6wu.ipfs.dweb.link/#/pools/0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9/0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8/0xeC8FD921a53559d7F10CC8606326fb8A192c9318?chainId=42161

**Comment by luzzif** [comment]
Oh ok, I initially didn't get that. I've updated the PR now, the latest preview build should always show the tooltip.

**Review by zamli — APPROVED** [review]

**Pull request merged**
