### PR TITLE
Add icon to expand more options on small screens

### PR DESCRIPTION
**Pull request by AugustoL**

### CODE REVIEW

**Comment by AugustoL** [comment]
@zamli the popup shows the links that are hidden in smaller screens, and I also change the align of header items to right in small screens.

Colors should be changed after new theme is implemented, Is this good enough for now?

**Comment by zamli** [comment]
Seems to be good enough. Just a bug, I can't close down the settings window. Same for you?

**Comment by zamli** [comment]
Also the modals dont have any backdrop/overlay. Maybe @luzzif and can do those for all modals

**Comment by AugustoL** [comment]
> Seems to be good enough. Just a bug, I can't close down the settings window. Same for you?

weird, I can, you clicking the X and extra links icon on the top?

**Comment by AugustoL** [comment]
> Also the modals dont have any backdrop/overlay. Maybe @luzzif and can do those for all modals

Yes

**Comment by zamli** [comment]
> > Seems to be good enough. Just a bug, I can't close down the settings window. Same for you?
> 
> weird, I can, you clicking the X and extra links icon on the top?

tried this again. I think the menu is closable. but the bottom settings is not.

f6nuDUhtXo

**Review by zamli — APPROVED** [review]

**Pull request merged**
