### PR TITLE
liquidity page - initial commitment

### PR DESCRIPTION
**Pull request by jsockchain**

### CODE REVIEW

**Comment by zamli** [comment]
image
18 px padding between here

**Comment by zamli** [comment]
image
center the 3 inside the circle

**Comment by zamli** [comment]
image
make this box same style. Maybe you done that elsewhere and we can merge later. ignore if you don't this already

**Comment by zamli** [comment]
image
buttons should reach all the way to text box

**Comment by jsockchain** [comment]
This is liquidity page. 
Should be able to check here - https://deploy-preview-182--swapr.netlify.app/#/liquidity/USDC/ETH

**Comment by zamli** [comment]
@jsockchain 
Passed proposal is right!
Failed proposal is right!
Active proposal is wrong. It shouldn't be positive or negative color for the background on button
This is the look of an active proposal with no outcome:
image

**Comment by zamli** [comment]
add letter spacing 0.08em(or whatever measurment you are using)
image

**Comment by zamli** [comment]
image
make color "text dark mode #4" or #C0BAF6

**Comment by zamli** [comment]
image
make the clock icon also green/red

**Review by zamli — APPROVED** [review]

**Comment by luzzif** [comment]
Closing because it has been worked on in #180

**Pull request closed without merging**
