### PR TITLE
Feature/governance card redesign

### PR DESCRIPTION
**Pull request by jsockchain**
https://github.com/levelkdev/dxswap-dapp/issues/126

### CODE REVIEW

**Comment by jsockchain** [comment]
image
image

@zamli  For your reference.

**Review by luzzif — APPROVED** [review]

**Comment by luzzif** [comment]
Merging this and then `feature/governance` into `develop `because I need some components defined here for the liquidity mining. Once merged to `develop`, I will disable the governance header link again and sync `feature/governance`, so that @jsockchain can continue his work (nice work btw!)

**Comment by zamli** [comment]
@jsockchain spacing in between cards should be 8px.
image

**Comment by zamli** [comment]
make the styling like the design
image

**Comment by zamli** [comment]
give cards more square look like the design(give them more height.
When clicking on governance, go back one step
image

**Pull request merged**
