### PR TITLE
Add basic layout for swapr bridge

### PR DESCRIPTION
**Pull request by alexcherman**

### CODE REVIEW

**Review by luzzif — APPROVED** [review]

**Comment by zamli** [comment]
image
This should say: Bridge

**Comment by zamli** [comment]
Can we use the same drop down for the network-switcher?
See here
https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=3183%3A21125
image

**Comment by alexcherman** [comment]
> Can we use the same drop down for the network-switcher?
> See here
> https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=3183%3A21125
> image

Have we already used this component somewhere?

**Comment by zamli** [comment]
> > Can we use the same drop down for the network-switcher?
> > See here
> > https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=3183%3A21125
> > image
> 
> Have we already used this component somewhere?

yes. Its used on the network switcher today. Disconnect your wallet to see it

**Pull request closed without merging**
