### PR TITLE
feature/wallet disconnect btn

### PR DESCRIPTION
**Pull request by natonnelier**
Screen-Recording-2021-12-17-at-10 50 55

### CODE REVIEW

**Review by karczuRF — APPROVED** [review]

**Comment by MilanVojnovic95** [comment]
Tested and working properly.

**Comment by karczuRF** [comment]
I've just solved merge conflicts and when testing I've noticed one thing. The green indicator is gray for connected network. For wallet popover is ok, it's green. The wallet name is not disabled, because can be clicked to see account details. 
Quick fix for not changing indicator color is needed.


image
image

**Comment by zamli** [comment]
> I've just solved merge conflicts and when testing I've noticed one thing. The green indicator is gray for connected network. For wallet popover is ok, it's green. The wallet name is not disabled, because can be clicked to see account details.
> 
> Is it ok like this or quick fix for not changing indicator color is needed? @zamli
> 
> image image

I think thats because its making the connected network lower in opacity. Thats the old way of showing how a connected network is. Keep the connected network at 100% opacity and unclickable. Wallet should behave the same.

not connected, connected state
image

**Review by denciu — APPROVED** [review]

**Comment by MilanVojnovic95** [comment]
Tested again and everything works ok. The wallet disconect behaves as it should and also the network and wallet indicators work well.

**Pull request merged**
