### PR TITLE
Change mobile navigation styles

### PR DESCRIPTION
**Pull request by alexcherman**
Screenshot 2021-06-21 at 11 16 41

### CODE REVIEW

**Comment by zamli** [comment]
image
Wrong network text is too close to the other button. Can we try making it more like this design
image

**Comment by alexcherman** [comment]
yes, of course

**Comment by zamli** [comment]
image
when scaling down to "tablet" mode the navigation jumps too close to the browser edge. Can we make it have the same distance as desktop

**Comment by zamli** [comment]
image
pressing connect wallet button on swap box now does nothing. We can use the same drop down as the navigation connect button.

on desktop
image


On mobile
image

**Pull request closed without merging**
