### PR TITLE
fix page crashes if incorrect gas price value

### LINKED ISSUE #555: The page crashes after entering an incorrect gas price in the settings
Version: 8.1 and 9

Steps to recreate - open Settings -> in "preferred gas price" type any sign that should not be accepted by this input (like minus sign or dot)

Result - the page turns white

To do - apply some kind of error message or disable signs that are not acceptable in this input without page crashing. Remember - all inputs within the application should display the same form of error message.

### PR DESCRIPTION
**Pull request by karczuRF**
Closes #555

### CODE REVIEW

**Review by Mi-Lan — APPROVED** [review]
LGTM! Doesn't throw error anymore

**Review by denciu — APPROVED** [review]

**Comment by 0xVenky** [comment]
No more errors seen :) Good to merge after @kingalg gives it a check

**Comment by kingalg** [comment]
It's not crashing the page anymore, so thats good. I have two points to discuss:

1. Can we have an error message below error? Right now it's below transaction deadline not, gas price. Should be below gas price.
Screenshot 2022-01-26 at 12 08 28

 2. We don't have a gas price at all on test networks (but we don't have it in currently published version as well so it looks like it didn't changed with this fix). Is it a bug that slipped through my checks or it should work like that on testnets? I think that it's a bug, but please confirm @0xVenky 
 Screenshot 2022-01-26 at 12 05 45

**Comment by karczuRF** [comment]
@kingalg good points! What about creating new issues and solving them in separate PRs? I could merge and close this fix now.

**Comment by 0xVenky** [comment]
Regarding 2, the gasPrice is only for Mainnet that willbe of impact. On other networks, I dont think gasPrice is of the that important. We can ignore that. The same can be observed on Arbitrum and Gnosis Chain as well. :)

**Comment by kingalg** [comment]
> Regarding 2, the gasPrice is only for Mainnet that willbe of impact. On other networks, I dont think gasPrice is of the that important. We can ignore that. The same can be observed on Arbitrum and Gnosis Chain as well. :)

That's ok but then to test it correctly in all possible scenarios in swaps we need to consider one of below:
1) Send me some funds so I can test how this functionality is behaving in different scenarios. (for example - slippage tolerance crashes the page as well but only if you input negative number and then try to swap some funds)
2) Add gas price to some test net.
3) Not cover this functionality with tests at all.

I would prefer 1 or 2. Third option is a risk especially that it's impacting "money" directly.

**Comment by karczuRF** [comment]
I've changed position of the error message, now is just below the error.

**Review by mix1o — APPROVED** [review]

**Pull request merged**
