### PR TITLE
style: Updated new styling for navigation connector

### LINKED ISSUE #338: a

### PR DESCRIPTION
**Pull request by Mi-Lan**
closes #338 
New style:

Screenshot 2021-09-14 at 19 34 04

### CODE REVIEW

**Comment by zamli** [comment]
image
make these also 8px radius.

**Comment by zamli** [comment]
it also looks like they are not centered 
image

**Comment by Mi-Lan** [comment]
Seems that issue with it not being centered is related to line-height....Couldn't quite figure it out.

**Review by zamli — CHANGES_REQUESTED** [review]
Let me get back to you for changes on this one. I need to take a second look at the design

**Comment by adamazad** [comment]
Should we close this due to inactivity/invalid? @zamli @Mi-Lan

**Comment by Mi-Lan** [comment]
> Should we close this due to inactivity/invalid? @zamli @Mi-Lan

Im fine with that. @zamli What do you think Zett? Since we are removing the claim airdrop feature it makes sense...

**Comment by 0xVenky** [comment]
Not relevant anymore. So closing this PR for now without merging.

**Pull request closed without merging**
