### PR TITLE
Make pairs&reward screen responsive

### PR DESCRIPTION
**Pull request by alexcherman**

### CODE REVIEW

**Comment by luzzif** [comment]
Looking at the code, things look fine. I have some feedback on the frontend itself:

- The pagination widget seems to be not perfectly centered. Looking closer, there's some left padding on the thing which pushes it right.
- The "my pairs" filter shouldn't be shown if no wallet is connected.
- If I switch to an empty filter view (for example the "my pairs" one with no wallet connected), the whole view "collapses". Would be nice to keep the thing with a somewhat fixed height to avoid the thing from happening. The same thing happens when less than 7 items are to be shown in the desktop view for example, i.e. when only 1 or 2 rows of data out of 3 have to be shown.

**Comment by zamli** [comment]
image
There is something wierd that happened to the APY bar. It is suppose to be to the top right.

**Comment by zamli** [comment]
image
Looks like the padding is uneven.
The design is like this
image

**Comment by zamli** [comment]
Change this to "Create Rewards"
image

**Comment by alexcherman** [comment]
I changed the button text but there is still not enough space. Can we position these buttons in one column?
Screenshot 2021-07-16 at 15 20 00

**Comment by alexcherman** [comment]
Hey @luzzif. I talked with @zamli and he said that we should leave like this. Do you have any other comments?

> * If I switch to an empty filter view (for example the "my pairs" one with no wallet connected), the whole view "collapses". Would be nice to keep the thing with a somewhat fixed height to avoid the thing from happening. The same thing happens when less than 7 items are to be shown in the desktop view for example, i.e. when only 1 or 2 rows of data out of 3 have to be shown.

**Pull request merged**
