### PR TITLE
Show rewards list when not connected

### LINKED ISSUE #653: Rewards page should be shown when wallet is not connected
On Beta 10, on [rewards page](https://swapr.eth.limo/#/rewards), the user has to connect the wallet to see available pairs with rewards.

image

**AC**

- User can see rewards without connecting wallet

### PR DESCRIPTION
**Pull request by Mi-Lan**
# Summary

Fixes #653 

*Show all the rewards pair instead of connect button when you are not connected*
Screenshot 2022-03-07 at 17 39 24

  # To Test

1. Disconnect wallet
2. Go to rewards section
2. Check if rewards list appears even when wallet is not connected

### CODE REVIEW

**Comment by MilanVojnovic95** [comment]
> # Summary
> Fixes #653
> 
> _Show all the rewards pair instead of connect button when you are not connected_ Screenshot 2022-03-07 at 17 39 24
> 
> # To Test
> 1. Disconnect wallet
> 2. Go to rewards section
> 3. Check if rewards list appears even when wallet is not connected

@Mi-Lan 
Tested and rewards pairs are not displayed now
image

**Comment by Mi-Lan** [comment]
> > # Summary
> > Fixes #653
> > _Show all the rewards pair instead of connect button when you are not connected_ Screenshot 2022-03-07 at 17 39 24
> > # To Test
> > 
> > 1. Disconnect wallet
> > 2. Go to rewards section
> > 3. Check if rewards list appears even when wallet is not connected
> 
> @Mi-Lan Tested and rewards pairs are not displayed image

There are no rewards on mainnet currently. Try it with wallet connected it is the same...

**Comment by MilanVojnovic95** [comment]
> > > # Summary
> > > Fixes #653
> > > _Show all the rewards pair instead of connect button when you are not connected_ Screenshot 2022-03-07 at 17 39 24
> > > # To Test
> > > 
> > > 1. Disconnect wallet
> > > 2. Go to rewards section
> > > 3. Check if rewards list appears even when wallet is not connected
> > 
> > 
> > @Mi-Lan Tested and rewards pairs are not displayed image
> 
> There are no active rewards on mainnet currently, but you can see it shows expired ones. Try it with wallet connected it is the same...

You're right, it's the same with me now. Displays rewards pair when wallet is not connected.

**Comment by Mi-Lan** [comment]
> Hey, we dont have active reward campaigns in Mainnet now. When I switch to Arbitrum or Gnosis chain, I can see rewards page. Can you guys check there? 🤔 @MilanVojnovic95

🤔  Yeah thats expected behaviour its what I worked on...So it doesn't show the connect wallet button...

**Review by karczuRF — APPROVED** [review]

**Review by berteotti — APPROVED** [review]

**Review by denciu — APPROVED** [review]

**Pull request merged**
