### PR TITLE
Update xdai & arbitrum logotypes

### PR DESCRIPTION
**Pull request by alexcherman**

### CODE REVIEW

**Review by luzzif — APPROVED** [review]
Lgtm

**Comment by zamli** [comment]
What about ethereum logo?
https://github.com/levelkdev/dxswap-dapp/issues/368

**Comment by alexcherman** [comment]
@zamli  Could you send me ethereum logo?

**Comment by zamli** [comment]
> @zamli Could you send me ethereum logo?

https://github.com/levelkdev/dxswap-dapp/issues/368
It is in the issue here, right click save the eth logo

**Comment by alexcherman** [comment]
@zamli ah, now I see it. It has the same color as a background. I'll update it in a separate PR.

**Comment by zamli** [comment]
> @zamli ah, now I see it. It has the same color as a background. I'll update it in a separate PR.

oh you have github in white? That explains it

**Pull request merged**
