### PR TITLE
Settings dropdown spaces

### PR DESCRIPTION
**Pull request by alexcherman**
Before:
paste

After:
Screenshot 2021-07-02 at 17 05 00

### CODE REVIEW

**Review by zamli — APPROVED** [review]

**Comment by luzzif** [comment]
I can see a `width: 100vw;` on the dialog content, but on bigger mobile viewports the modal looks like this:
image

Is it wanted @zamli?

**Comment by alexcherman** [comment]
I'll check it

**Comment by alexcherman** [comment]
> I can see a `width: 100vw;` on the dialog content, but on bigger mobile viewports the modal looks like this:
> image

@luzzif  Do you mean there is less space between "transaction deadline", "interface settings" and "toggle expert mode" lines than in was before?

**Comment by alexcherman** [comment]
@luzzif  Let me know if you meant something else.

**Comment by luzzif** [comment]
I just expected the mobile menu to cover ALL of the viewport's width

**Comment by zamli** [comment]
in landscape mode the menu apears behind objects and some buttons and items can't be clicked on. I suggest us to always keep it at the top infront of everything else.
image

**Comment by zamli** [comment]
Looks and works great!

**Pull request merged**
